In [1]:
import sys,os
sys.path.append(os.pardir)
from cmf.crmf import CRMF
import numpy as np

In [2]:
A = np.array([4, 5, -4, -2, 1, 3, -5, -1, 0, -4])
B = 2 * np.ones(A.shape)

In [3]:
CRMF.shrink(A, B)

array([ 2,  3, -2,  0,  0,  1, -3,  0,  0, -2])

In [4]:
n_sheets = 2
n_rows = 3
n_cols = 4
A = np.array(range(n_sheets * n_rows * n_cols)).reshape([n_sheets, n_rows, n_cols])
b = np.array(range(n_cols))

In [5]:
n_rows = 3
n_cols = 4
A = np.array(range(n_rows * n_cols)).reshape([n_rows, n_cols])
b = np.array(range(n_cols))

In [6]:
print(A)
print(b[np.newaxis, :])
print(A * b[np.newaxis, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]


In [7]:
np.array(range(10))[:, np.newaxis] * np.array(range(20))[np.newaxis, :] 

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
         39,  42,  45,  48,  51,  54,  57],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
         52,  56,  60,  64,  68,  72,  76],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
         65,  70,  75,  80,  85,  90,  95],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
         78,  84,  90,  96, 102, 108, 114],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
         91,  98, 105, 112, 119, 126, 133],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  

In [28]:
A = (np.array(range(120))).reshape([30,4])

In [29]:
np.concatenate([np.roll(A, i, axis=0) for i in range(-2, 2)], axis = 1)

array([[  8,   9,  10,  11,   4,   5,   6,   7,   0,   1,   2,   3, 116,
        117, 118, 119],
       [ 12,  13,  14,  15,   8,   9,  10,  11,   4,   5,   6,   7,   0,
          1,   2,   3],
       [ 16,  17,  18,  19,  12,  13,  14,  15,   8,   9,  10,  11,   4,
          5,   6,   7],
       [ 20,  21,  22,  23,  16,  17,  18,  19,  12,  13,  14,  15,   8,
          9,  10,  11],
       [ 24,  25,  26,  27,  20,  21,  22,  23,  16,  17,  18,  19,  12,
         13,  14,  15],
       [ 28,  29,  30,  31,  24,  25,  26,  27,  20,  21,  22,  23,  16,
         17,  18,  19],
       [ 32,  33,  34,  35,  28,  29,  30,  31,  24,  25,  26,  27,  20,
         21,  22,  23],
       [ 36,  37,  38,  39,  32,  33,  34,  35,  28,  29,  30,  31,  24,
         25,  26,  27],
       [ 40,  41,  42,  43,  36,  37,  38,  39,  32,  33,  34,  35,  28,
         29,  30,  31],
       [ 44,  45,  46,  47,  40,  41,  42,  43,  36,  37,  38,  39,  32,
         33,  34,  35],
       [ 48,  49,  50,  51,  4

In [6]:
import numpy as np
from sklearn.decomposition import PCA
X = np.reshape(np.arange(12, dtype='float'), (3, 4))
pca = PCA()
pca.fit(X)
W = np.array(X)
W[2, 1] = np.nan
# Z = pca.transform(W)
# V = pca.inverse_transform(Z)

In [1]:
import pyper

In [2]:
r = pyper.R(use_pandas='True', use_numpy=True)

In [68]:
# r('source("http://bioconductor.org/biocLite.R")')

'print("R command at time: 1507098938.797265")\r\n[1] "R command at time: 1507098938.797265"\r\n> try({source("http://bioconductor.org/biocLite.R")})\r\nBioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help\r\n'

In [69]:
# r('biocLite("pcaMethods")')

'> try({biocLite("pcaMethods")})\r\nBioC_mirror: https://bioconductor.org\r\nUsing Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.2 (2017-09-28).\r\nInstalling package(s) \'pcaMethods\'\r\n'

In [50]:
r('library(pcaMethods)')

'try({library(pcaMethods)})\r\n'

In [51]:
r('listPcaMethods()')

'try({listPcaMethods()})\r\n [1] "svd"          "nipals"       "rnipals"      "bpca"         "ppca"        \r\n [6] "svdImpute"    "robustPca"    "nlpca"        "llsImpute"    "llsImputeAll"\r\n'

In [84]:
Z = np.reshape(np.arange(12, dtype='float'), (6, 2))
W = np.reshape(np.arange(1, 13, dtype='float'), (6, 2)) / 2.
Th = np.reshape(np.arange(8, dtype='float'), (2, 4))
X = Z @ Th
X += np.random.normal(0, 0.01, X.shape)
Y = W @ Th
F = np.ones(X.shape)
F[0][1] = 0
F[1][1] = 0
F[1][3] = 0
F[2][0] = 0
F[4][2] = 0
F[5][0] = 0
# print(X, Y, F)

In [85]:
r.assign('X', X)
r.assign('Y', Y)
r.assign('F', F)
r('Ymiss <- Y')
r('Ymiss[F==0] <- NA')
# r('print(Ymiss)')

'try({Ymiss[F==0] <- NA})\r\n'

In [108]:
r('Xpca <- pca(X, method="svd", nPcs=2, threshold = 1e-05)')

'try({Xpca <- pca(X, method="svd", nPcs=2, threshold = 1e-05)})\r\n'

In [109]:
r('print(Xpca@completeObs)')

'try({print(Xpca@completeObs)})\r\n          [,1]      [,2]     [,3]       [,4]\r\n[1,]  3.987602  5.003313  5.99307   7.002383\r\n[2,] 11.988555 16.992501 21.99176  27.019266\r\n[3,] 19.996882 28.999022 38.00758  46.994565\r\n[4,] 28.000402 41.006585 54.01529  66.996480\r\n[5,] 35.988282 53.010112 69.98546  87.001479\r\n[6,] 44.010209 65.010762 86.01395 106.996489\r\n'

In [110]:
r('Ypredict <- predict(Xpca, Ymiss)')

'try({Ypredict <- predict(Xpca, Ymiss)})\r\n'

In [111]:
r('print(Ypredict)')

'try({print(Ypredict)})\r\n$scores\r\n            PC1         PC2\r\n[1,] -59.670951  -2.4306019\r\n[2,] -21.231507 -26.6670022\r\n[3,] -39.058081   3.9053740\r\n[4,] -27.626993  -0.3116121\r\n[5,]  -9.118707   4.4393520\r\n[6,]   1.765610  -0.3175061\r\n\r\n$x\r\n          [,1]     [,2]     [,3]     [,4]\r\n[1,]  6.895238 10.81417 11.86701 17.96536\r\n[2,]  8.844698 28.25556 16.33887 59.64262\r\n[3,] 14.733610 18.77432 27.38985 27.92891\r\n[4,] 16.364096 23.74560 30.74988 38.40702\r\n[5,] 23.072539 30.96060 44.05095 47.95430\r\n[6,] 24.364464 35.74752 46.74680 58.40632\r\n\r\n'

In [112]:
Yhat = r.get('Ypredict$x')
print(Yhat)

[[  6.89523788  10.81417117  11.86701221  17.96536311]
 [  8.84469764  28.25555614  16.33887205  59.64262486]
 [ 14.73360986  18.77432167  27.38985472  27.92891127]
 [ 16.36409618  23.74560444  30.74987801  38.40702455]
 [ 23.0725393   30.96059818  44.05095267  47.95429508]
 [ 24.36446374  35.747516    46.74680319  58.40631851]]


In [21]:
r('print(Xhat@completeObs)')

'try({print(Xhat@completeObs)})\r\n     [,1]     [,2] [,3] [,4]\r\n[1,]    4 15.00254    6    7\r\n[2,]   12 17.00000   22   27\r\n[3,]   20 29.00000   38   47\r\n[4,]   28 41.00000   54   67\r\n[5,]   36 53.00000   70   87\r\n[6,]   44 65.00000   86  107\r\n'

In [24]:
Xhat = r.get('Xhat@completeObs')
print(Xhat)

[[   4.          15.0025361    6.           7.       ]
 [  12.          17.          22.          27.       ]
 [  20.          29.          38.          47.       ]
 [  28.          41.          54.          67.       ]
 [  36.          53.          70.          87.       ]
 [  44.          65.          86.         107.       ]]


In [47]:
r('rm(list=ls())')

'try({rm(list=ls())})\r\n'

In [45]:
r('print(What)')

'> print("R command at time: 1507097999.7916412")\r\n[1] "R command at time: 1507097999.7916412"\r\n> try({print(What)})\r\n'

In [120]:
a = [list(range(0,3)), list(range(5,8))]
tuple(a)
for b in zip(*tuple(a)):
    print(b[0], b[1])

0 5
1 6
2 7
