In [1]:
import sys,os
sys.path.append(os.pardir)
from cmf.crmf import CRMF
import numpy as np

In [2]:
A = np.array([4, 5, -4, -2, 1, 3, -5, -1, 0, -4])
B = 2 * np.ones(A.shape)

In [3]:
CRMF.shrink(A, B)

array([ 2,  3, -2,  0,  0,  1, -3,  0,  0, -2])

In [4]:
n_sheets = 2
n_rows = 3
n_cols = 4
A = np.array(range(n_sheets * n_rows * n_cols)).reshape([n_sheets, n_rows, n_cols])
b = np.array(range(n_cols))

In [5]:
n_rows = 3
n_cols = 4
A = np.array(range(n_rows * n_cols)).reshape([n_rows, n_cols])
b = np.array(range(n_cols))

In [6]:
print(A)
print(b[np.newaxis, :])
print(A * b[np.newaxis, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]
[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]]


In [7]:
np.array(range(10))[:, np.newaxis] * np.array(range(20))[np.newaxis, :] 

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
         39,  42,  45,  48,  51,  54,  57],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
         52,  56,  60,  64,  68,  72,  76],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
         65,  70,  75,  80,  85,  90,  95],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
         78,  84,  90,  96, 102, 108, 114],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
         91,  98, 105, 112, 119, 126, 133],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  

In [28]:
A = (np.array(range(120))).reshape([30,4])

In [29]:
np.concatenate([np.roll(A, i, axis=0) for i in range(-2, 2)], axis = 1)

array([[  8,   9,  10,  11,   4,   5,   6,   7,   0,   1,   2,   3, 116,
        117, 118, 119],
       [ 12,  13,  14,  15,   8,   9,  10,  11,   4,   5,   6,   7,   0,
          1,   2,   3],
       [ 16,  17,  18,  19,  12,  13,  14,  15,   8,   9,  10,  11,   4,
          5,   6,   7],
       [ 20,  21,  22,  23,  16,  17,  18,  19,  12,  13,  14,  15,   8,
          9,  10,  11],
       [ 24,  25,  26,  27,  20,  21,  22,  23,  16,  17,  18,  19,  12,
         13,  14,  15],
       [ 28,  29,  30,  31,  24,  25,  26,  27,  20,  21,  22,  23,  16,
         17,  18,  19],
       [ 32,  33,  34,  35,  28,  29,  30,  31,  24,  25,  26,  27,  20,
         21,  22,  23],
       [ 36,  37,  38,  39,  32,  33,  34,  35,  28,  29,  30,  31,  24,
         25,  26,  27],
       [ 40,  41,  42,  43,  36,  37,  38,  39,  32,  33,  34,  35,  28,
         29,  30,  31],
       [ 44,  45,  46,  47,  40,  41,  42,  43,  36,  37,  38,  39,  32,
         33,  34,  35],
       [ 48,  49,  50,  51,  4